version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - '5432:5432'
    restart: always
    env_file:
      - ./.env
    volumes:
      - type: volume
        source: postgres-db
        target: /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: app
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./.env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - type: bind
        source: ./app
        target: /app/app
      - type: bind
        source: ./templates
        target: /app/templates
      - type: bind
        source: ./static
        target: /app/static
      - type: bind
        source: ./alembic
        target: /app/alembic
      - type: bind
        source: ./alembic.ini
        target: /app/alembic.ini
    restart: always

volumes:
  postgres-db:
    driver: local